require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BotsController do

  # This should return the minimal set of attributes required to create a valid
  # Bot. As you add validations to Bot, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BotsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all bots as @bots" do
      bot = Bot.create! valid_attributes
      get :index, {}, valid_session
      assigns(:bots).should eq([bot])
    end
  end

  describe "GET show" do
    it "assigns the requested bot as @bot" do
      bot = Bot.create! valid_attributes
      get :show, {:id => bot.to_param}, valid_session
      assigns(:bot).should eq(bot)
    end
  end

  describe "GET new" do
    it "assigns a new bot as @bot" do
      get :new, {}, valid_session
      assigns(:bot).should be_a_new(Bot)
    end
  end

  describe "GET edit" do
    it "assigns the requested bot as @bot" do
      bot = Bot.create! valid_attributes
      get :edit, {:id => bot.to_param}, valid_session
      assigns(:bot).should eq(bot)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Bot" do
        expect {
          post :create, {:bot => valid_attributes}, valid_session
        }.to change(Bot, :count).by(1)
      end

      it "assigns a newly created bot as @bot" do
        post :create, {:bot => valid_attributes}, valid_session
        assigns(:bot).should be_a(Bot)
        assigns(:bot).should be_persisted
      end

      it "redirects to the created bot" do
        post :create, {:bot => valid_attributes}, valid_session
        response.should redirect_to(Bot.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bot as @bot" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bot.any_instance.stub(:save).and_return(false)
        post :create, {:bot => {}}, valid_session
        assigns(:bot).should be_a_new(Bot)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Bot.any_instance.stub(:save).and_return(false)
        post :create, {:bot => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bot" do
        bot = Bot.create! valid_attributes
        # Assuming there are no other bots in the database, this
        # specifies that the Bot created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Bot.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => bot.to_param, :bot => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested bot as @bot" do
        bot = Bot.create! valid_attributes
        put :update, {:id => bot.to_param, :bot => valid_attributes}, valid_session
        assigns(:bot).should eq(bot)
      end

      it "redirects to the bot" do
        bot = Bot.create! valid_attributes
        put :update, {:id => bot.to_param, :bot => valid_attributes}, valid_session
        response.should redirect_to(bot)
      end
    end

    describe "with invalid params" do
      it "assigns the bot as @bot" do
        bot = Bot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bot.any_instance.stub(:save).and_return(false)
        put :update, {:id => bot.to_param, :bot => {}}, valid_session
        assigns(:bot).should eq(bot)
      end

      it "re-renders the 'edit' template" do
        bot = Bot.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Bot.any_instance.stub(:save).and_return(false)
        put :update, {:id => bot.to_param, :bot => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bot" do
      bot = Bot.create! valid_attributes
      expect {
        delete :destroy, {:id => bot.to_param}, valid_session
      }.to change(Bot, :count).by(-1)
    end

    it "redirects to the bots list" do
      bot = Bot.create! valid_attributes
      delete :destroy, {:id => bot.to_param}, valid_session
      response.should redirect_to(bots_url)
    end
  end

end
